import { Inter, Geist_Mono } from 'next/font/google'
import './styles.css'

const geistSans = Inter({
 // Geist no existe, usa Inter como alternativa
 subsets: ['latin'],
})

const geistMono = Geist_Mono({
 subsets: ['latin'],
})

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 return (
  <html lang='en'>
   <body className={`${geistSans.className} ${geistMono.className}`}>
    {children}
   </body>
  </html>
 )
}
